nmHoistingLimits: workspaces
nodeLinker: node-modules
npmPublishRegistry: https://registry.npmjs.org
npmAuthToken: ${NPM_TOKEN-deadbeef-dead-beef-dead-beefdeadbeef}
npmPublishAccess: public

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"

yarnPath: .yarn/releases/yarn-3.6.1.cjs
